language: ruby
rvm:
- 2.3.1

after_success:
- >
  [ "${TRAVIS_PULL_REQUEST}" != "false" ] &&
    PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} \
      bundle exec pronto run -f github_status github_pr -c origin/${TRAVIS_BRANCH}
